### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by helio-frota**
Related to: https://github.com/npm/npm/issues/14012

### CODE REVIEW

**Comment by silverwind** [comment]
This doesn't look right, from the README:

> Remove the empty branches of a directory tree, optionally up to (but not including) a specified base directory

It should work with any directory, not just the special case of the home directory.

**Comment by helio-frota** [comment]
@silverwind hi, this fix is based on (which in the case I agree) :

> This is a severe bug – user software should never be removing $HOME

https://github.com/npm/npm/issues/14012#issuecomment-248120027

**Comment by helio-frota** [comment]
Also, added a quick fix on README.md , missing options parameter on example code.

**Comment by zkat** [comment]
@helio-frota sorry for the delay in getting around to this. Could you please add a test to verify this behavior? Otherwise lgtm

**Comment by helio-frota** [comment]
@zkat sorry the delay.

So I can't verify/reproduce in a `good way` using unit tests :/

So I've created a virtualbox env to test it and if we run the test with normal user we get this:

```
test/arguments.js ..................................... 5/5
test/base-leaf-mismatch.js ............................ 2/2
test/do-not-delete-home-dir.js { Error: EACCES: permission denied, rmdir '/home/foo'
at Error (native)
  errno: -13,
  code: 'EACCES',
  syscall: 'rmdir',
  path: '/home/foo' }
test/do-not-delete-home-dir.js ........................ 1/1
test/no-entries-file-no-purge.js .................... 19/19
test/no-entries-link-no-purge.js .................... 21/21
test/no-entries-no-purge.js ......................... 15/15
test/no-entries-with-link-purge.js .................. 17/17
test/no-entries-with-purge.js ....................... 16/16
test/other-directories-no-purge.js .................. 16/16
test/racy-entries-eexist.js ......................... 19/19
test/racy-entries-enotempty.js ...................... 19/19
test/racy-entries.js ................................ 19/19
total ............................................. 169/169

  169 passing (3s)
```

if we run as `root` and made a minimal mistake we lost the `/root` then we need to "setup" all again
1. wget nvm
2. nvm install 6
3. cp /somepath/fs-vacuum /root 
4. npm run test

I mean, the only way I've found to reproduce this is running the tests using root user (**not good**). 
( and virtualbox to avoid some disasters )

**Comment by zkat** [comment]
@helio-frota did you try just creating a mock directory and setting `process.env.HOME` to that? I'd be happy enough with a test for that case :)

**Comment by helio-frota** [comment]
@zkat thanks for the mocking tip. :+1: 
test added.

**Comment by zkat** [comment]
This has been released as part of `fs-vacuum@1.2.10`, and I'm gonna go shove the version bump into the integration branch in npm, so it'll end up in the next release :)

Thanks a bunch!

**Pull request merged**
